### ISSUE TITLE
Computing only metrics produces an exception

### ISSUE THREAD

**Issue by alejandrofdez-us** [felescgon/best-epoch-selector#13]
TypeError: cannot pickle 'dict_keys' object

**Comment by felescgon** [comment]
As our arguments.figures are optional, we should use '[]' instead of 'None' when we don't compute any figures:
![image](https://github.com/felescgon/best-epoch-selector/assets/72603609/a89099b8-2589-4138-92ba-53b0bbc03871)
Bug was mistakenly placed when fixing a similar bug in d374466bf17765b3603a634d533a053b43c2b3a0.
