### ISSUE TITLE
¿Wrong number of elements needed for the intersection?

### ISSUE THREAD

**Issue by alejandrofdez-us** [felescgon/best-epoch-selector#8]
I've manually checked that the experiment: `timegan-pytorch/alibaba2018/GRU-seq_len-288//num_layers-3-hidden_dim-128-batch_size-32-module-gru-emb_sup_e-100/` **may*** have needed only 7 elements in each bucket for the intersection. But the results show the following:
```Json
  "/home/afdez/experiments/timegan-pytorch/alibaba2018/GRU-seq_len-288/num_layers-3-hidden_dim-128-batch_size-32-module-gru-emb_sup_e-100/model": {
    "best_epochs": ["epoch_42", "epoch_7"],
    "intersection_experiments_n": 10
  }
```
*my old computation of dtw was wrong, that is why i cannot assure it is true, but we may need to debug it to check.

**Comment by felescgon** [comment]
Although it is not usual, it may happen naturally as in this example (checked and debugged):
| best_dtw  | best_js |
| ------------- | ------------- |
| **epoch_42**  | X  |
| **epoch_7** | **epoch_42**  |
| X | X  |
| X | X  |
| X | X  |
| X | X  |
| X | **epoch_7**  |
Intersection must be done with 7 rows in order to extract the 2 best epochs.
